apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: dev
rules:
  - apiGroups: ["extensions","apps"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: dev
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io